@startditaa -E -r
'
' Copyright (c) 2017-2018 Tallence AG and the authors
'
' This is free software; you can redistribute it and/or
' modify it under the terms of the GNU Lesser General Public
' License version 2.1, as published by the Free Software
' Foundation.  See file COPYING.

/---------------------------------------------------------------------------\
|                    Dovecot IMAP4/POP3/LMTP/LDA Process                    |
\+-------------------------------------------------------------------------+/
 |                           Dovecot Storage API                           |
 \+-----------------------------------------------------------------------+/
  |                        Dovecot rbox Storage Plugin               cF84 |
  +------------------+---------------+--------------+--------------------+/
  |     librmb   cF84|               :              |  Dovecot lib—index |
  \+----------------+/               :              \----------+---------/
   |   librados c9DE|                :                         |
   \-----+----------/                :                         v
         |                           :              /---------------------\
         |                           V              |       CephFS    c9DE|
         |                   /---------------\      +---------------------+
         |                   :    RFC5322    |      |    Linux Kernel cCCC|
         |  RFC 5322 Mails   | mail cache on |      \----------+----------/
         |                   | local storage |                 |
         |                   \---------------/                 |
         |                                                     |
/--------|-----------------------------------------------------|------------\
|        v                                                     v            |
|/---------------------\                             /---------------------\|
|| /-\ /-\ /-\ /-\ /-\ |                             | /-\ /-\ /-\ /-\ /-\ ||
|| | | |M| | | | | | | |                             | | | |M| | | | | |Y| ||
|| \-/ \-/ \-/ \-/ \-/ |                             | \-/ \-/ \-/ \-/ \-/ ||
|| cF87                |                             | cF87                ||
|| /-\ /-\ /-\ /-\ /-\ |                             | /-\ /-\ /-\ /-\ /-\ ||
|| | | |M| | | | | | | |                             | | | |M| | | | | | | ||
|| \-/ \-/ \-/ \-/ \-/ |                             | \-/ \-/ \-/ \-/ \-/ ||
||      Mail Pool      |       RADOS Cluster         |     CephFS Pool     ||
|\---------------------/                             \---------------------/|
\---------------------------------------------------------------------------/

@endditaa