@startditaa -E -r

   /-----------------\
   | Mail User Agent |
   \--------+--------/
            |
            | IMAP/POP
            v
 /-----------------------\
 |Ceph Client            |
 | /-------------------\ |
 | |      Dovecot      | |
 | |                   | |
 | +-------------------+ |
 | |rbox storage plugin| |
 | |cF84               | |
 | +----------+--------+ |
 | |   librmb | cephFS | |
 | |cF84      |   c9DE | |
 | +----------+--------+ |
 | |     librados  c9DE| |
 | \-------------------/ |
 |                   cEEE|
 \----------+------------/
            |
            |
            v
 /----------+-----------\
 |                      |
 |    RADOS Cluster     |
 |                  cF87|
 \----------------------/

@endditaa