@startditaa -E -r
'
' Copyright (c) 2017-2018 Tallence AG and the authors
'
' This is free software; you can redistribute it and/or
' modify it under the terms of the GNU Lesser General Public
' License version 2.1, as published by the Free Software
' Foundation.  See file COPYING.

   /-----------------\
   | Mail User Agent |
   \--------+--------/
            |
            | IMAP/POP
            v
 /-----------------------\
 |Ceph Client            |
 | /-------------------\ |
 | |      Dovecot      | |
 | |                   | |
 | +-------------------+ |
 | |rbox storage plugin| |
 | |cF84               | |
 | +----------+--------+ |
 | |   librmb | cephFS | |
 | |cF84      |   c9DE | |
 | +----------+--------+ |
 | |     librados  c9DE| |
 | \-------------------/ |
 |                   cEEE|
 \----------+------------/
            |
            |
            v
 /----------+-----------\
 |                      |
 |    RADOS Cluster     |
 |                  cF87|
 \----------------------/

@endditaa