name: container build

on:
  push:
    branches: 
      - '**'
  
jobs:
  container-job:

    runs-on: ubuntu-latest
    container: cephdovecot/travis-build-master-2.3:latest

    steps:
    - uses: actions/checkout@v2
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-dovecot=/usr/local/lib/dovecot --enable-maintainer-mode --enable-debug --with-integration-tests --enable-valgrind --enable-debug
    - name: build
      run:  make clean install